name: mens_health_app
description: App targeted towards men with the goal of improving mental and physical health
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Add the following Firebase dependencies
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.6

  flutter_native_splash: ^1.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/images/ponderbox.png
    - asset/images/IMG_5049.jpg
    - asset/images/IMG_5050.jpg
    - asset/images/IMG_5051.jpg
    

flutter_native_splash:
  color: "#42a5f5"
  image: asset/images/ponderbox.png
  fill: true